version: '3.8'

services:
  # Serwis do uruchamiania testów wydajnościowych
  performance-test:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./src/results:/app/src/results
    command: performance-test
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_TIMEOUT=20
    networks:
      - roadrunner-network
    depends_on:
      - visualizer
    restart: on-failure

  # Serwis do trenowania modelu LSTM
  lstm-trainer:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./src/prediction_models/lstm/models:/app/src/prediction_models/lstm/models
      - ./src/results:/app/src/results
    command: lstm-trainer
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - roadrunner-network
    depends_on:
      - performance-test
    restart: on-failure

  # Serwis do wizualizacji wyników
  visualizer:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./src/results:/app/src/results
    ports:
      - "8050:8050"  # Port dla Dash
    command: visualizer
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - roadrunner-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  roadrunner-network:
    driver: bridge

volumes:
  data:
  models:
  results: