version: '3.8'

services:
  # Serwis do wizualizacji wyników
  visualizer:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    command: >
      bash -c "pip install -r requirements.txt &&
               cd /app && 
               PYTHONPATH=/app python -u src/visualization_server.py"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  # Serwis do trenowania modelu LSTM
  lstm-trainer:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install -r requirements.txt &&
               cd /app && 
               PYTHONPATH=/app python -u src/predict_results.py"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

networks:
  default:
    driver: bridgefdsf